/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Media-Access-Control.h
 #	source generated by 4D Plugin Wizard
 #	Project : Media Access Control
 #	author : miyako
 #	2019/12/13
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_MEDIA_ACCESS_CONTROL_H
#define PLUGIN_MEDIA_ACCESS_CONTROL_H

#if _WIN32
#ifndef _WINDOWS_
#include <winsock2.h>
#include <windows.h>
#include <iphlpapi.h>
#pragma comment(lib, "iphlpapi.lib")
#endif
#endif

#include "4DPluginAPI.h"

#include "ARRAY_TEXT.h"
#include "C_TEXT.h"

#if VERSIONMAC
#include <SystemConfiguration/SCNetworkConfiguration.h>
//OS X 10.7
//https://developer.apple.com/library/mac/#documentation/CoreWLAN/Reference/CWInterface_reference/translated_content/CWInterface.html

//OS X 10.4
//http://developer.apple.com/library/mac/#documentation/Networking/Reference/SCNetworkConfiguration/Reference/reference.html

//OS X earlier
//https://developer.apple.com/library/mac/technotes/tn1103

//GetAdaptersAddresses
//http://msdn.microsoft.com/en-us/library/aa365915(VS.85).aspx
//http://stackoverflow.com/questions/221894/c-get-mac-address-of-network-adapters-on-vista
//http://msdn.microsoft.com/en-us/library/aa366062
//
#endif

#pragma mark -

void Get_hardware_address(PA_PluginParameters params);

#endif /* PLUGIN_MEDIA_ACCESS_CONTROL_H */
