/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-Media-Access-Control.cppF
 #	source generated by 4D Plugin Wizard
 #	Project : Media Access Control
 #	author : miyako
 #	2019/12/13
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-Media-Access-Control.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- Media Access Control
            
			case 1 :
				Get_hardware_address(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void Get_hardware_address(PA_PluginParameters params) {

    sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
    PackagePtr pParams = (PackagePtr)params->fParameters;
    
    ARRAY_TEXT Param1;
    ARRAY_TEXT Param2;
    ARRAY_TEXT Param3;
    ARRAY_TEXT Param4;
    C_TEXT returnValue;
    
    Param1.setSize(1);
    Param2.setSize(1);
    Param3.setSize(1);
    Param4.setSize(1);
    
#if VERSIONMAC
    NSArray *interfaces = NULL; // owned (Copy rule); released after the try block so a throw cannot leak it
#endif
    
    // Everything that can throw (allocation, string appends) is inside this block,
    // so the parameter write-back and PA_Return call below are always reached.
    try
    {
    #if VERSIONMAC
        interfaces = (NSArray *)SCNetworkInterfaceCopyAll();
        
        if(interfaces)
        {
            for(unsigned int i = 0; i < [interfaces count]; ++i)
            {
                SCNetworkInterfaceRef interface = (SCNetworkInterfaceRef)[interfaces objectAtIndex:i];
                
                if(interface)
                {
                    NSString *hardwareAddress = (NSString *)SCNetworkInterfaceGetHardwareAddressString(interface);
                    NSString *name = (NSString *)SCNetworkInterfaceGetBSDName(interface);
                    NSString *interfaceType = (NSString *)SCNetworkInterfaceGetInterfaceType(interface);
                    NSString *displayName = (NSString *)SCNetworkInterfaceGetLocalizedDisplayName(interface);
                    
                    if(!hardwareAddress) hardwareAddress = @"";
                    if(!name) name = @"";
                    if(!interfaceType) interfaceType = @"";
                    if(!displayName) displayName = @"";
                    
                    Param1.appendUTF16String(hardwareAddress);
                    Param2.appendUTF16String(interfaceType);
                    Param3.appendUTF16String(name);
                    Param4.appendUTF16String(displayName);
                    
                    if ([name isEqualToString:@"en0"])
                        returnValue.setUTF16String(hardwareAddress);
                }
            }
        }
    #else
        
        // Only the MAC address, type and names are needed, so skip the per-adapter address lists
        // (and the prefix list the old code requested). This keeps the required buffer small.
        const ULONG flags = GAA_FLAG_SKIP_UNICAST
                          | GAA_FLAG_SKIP_ANYCAST
                          | GAA_FLAG_SKIP_MULTICAST
                          | GAA_FLAG_SKIP_DNS_SERVER;
        
        // 15KB is Microsoft's recommended initial working buffer. The required size can still be larger
        // (many virtual adapters) or change between calls, so retry on ERROR_BUFFER_OVERFLOW.
        //http://msdn.microsoft.com/en-us/library/windows/desktop/aa365915(v=vs.85).aspx
        ULONG bufferSize = 15000;
        std::vector<uint8_t> buf;
        DWORD dwRetVal = ERROR_BUFFER_OVERFLOW;
        
        for(int attempt = 0; (attempt < 3) && (dwRetVal == ERROR_BUFFER_OVERFLOW); ++attempt)
        {
            buf.resize(bufferSize);
            dwRetVal = GetAdaptersAddresses(AF_UNSPEC,
                                            flags,
                                            NULL,
                                            (PIP_ADAPTER_ADDRESSES)&buf[0],
                                            &bufferSize); //updated to the required size on ERROR_BUFFER_OVERFLOW
        }
        
        if(dwRetVal == ERROR_SUCCESS)
        {
            PIP_ADAPTER_ADDRESSES pCurrAddresses = (PIP_ADAPTER_ADDRESSES)&buf[0];
            
            while(pCurrAddresses)
            {
                CUTF8String interfaceType;
                
                CUTF16String description;
                CUTF16String friendlyName;
                CUTF8String physicalAddress;
                
                switch(pCurrAddresses->IfType)
                {
                    case IF_TYPE_OTHER:
                        interfaceType = (const uint8_t *)"Other";
                        break;
                    case IF_TYPE_ETHERNET_CSMACD:
                        interfaceType = (const uint8_t *)"Ethernet";
                        break;
                    case IF_TYPE_ISO88025_TOKENRING:
                        interfaceType = (const uint8_t *)"Token-Ring";
                        break;
                    case IF_TYPE_PPP:
                        interfaceType = (const uint8_t *)"PPP";
                        break;
                    case IF_TYPE_SOFTWARE_LOOPBACK:
                        interfaceType = (const uint8_t *)"Software-Loopback";
                        break;
                    case IF_TYPE_ATM:
                        interfaceType = (const uint8_t *)"ATM";
                        break;
                    case IF_TYPE_IEEE80211:
                        interfaceType = (const uint8_t *)"IEEE80211";
                        break;
                    case IF_TYPE_TUNNEL:
                        interfaceType = (const uint8_t *)"Tunnel";
                        break;
                    case IF_TYPE_IEEE1394:
                        interfaceType = (const uint8_t *)"IEEE1394";
                        break;
                }
                
                // constructing a basic_string from a NULL pointer is undefined behaviour
                if(pCurrAddresses->Description)
                    description = (const PA_Unichar *)pCurrAddresses->Description;
                if(pCurrAddresses->FriendlyName)
                    friendlyName = (const PA_Unichar *)pCurrAddresses->FriendlyName;
                
                DWORD physicalAddressLength = pCurrAddresses->PhysicalAddressLength;
                
                if(physicalAddressLength == 6)
                {
                    char macAddress[512];
                    
                    sprintf_s(macAddress,
                                        sizeof(macAddress),
                                        "%02x:%02x:%02x:%02x:%02x:%02x",
                                        pCurrAddresses->PhysicalAddress[0],
                                        pCurrAddresses->PhysicalAddress[1],
                                        pCurrAddresses->PhysicalAddress[2],
                                        pCurrAddresses->PhysicalAddress[3],
                                        pCurrAddresses->PhysicalAddress[4],
                                        pCurrAddresses->PhysicalAddress[5]);
                    
                    physicalAddress = CUTF8String((const uint8_t *)macAddress, 17);
                    
                    if((pCurrAddresses->IfType == IF_TYPE_ETHERNET_CSMACD)
                         && (description.find((const PA_Unichar *)L"Bluetooth" ) == CUTF16String::npos))
                    {
                        returnValue.setUTF8String(&physicalAddress);
                    }
                    
                }
                
                Param1.appendUTF8String(&physicalAddress);
                Param2.appendUTF8String(&interfaceType);
                Param3.appendUTF16String(&description);
                Param4.appendUTF16String(&friendlyName);
                
                pCurrAddresses = pCurrAddresses->Next;
            }
        }
        
    #endif
    }
    catch(...)
    {
        // fall through: return whatever was collected so the host always gets its parameters and return value
    }
    
#if VERSIONMAC
    if(interfaces)
    {
        [interfaces release];
        interfaces = NULL;
    }
#endif
    
    Param1.toParamAtIndex(pParams, 1);
    Param2.toParamAtIndex(pParams, 2);
    Param3.toParamAtIndex(pParams, 3);
    Param4.toParamAtIndex(pParams, 4);
    returnValue.setReturn(pResult);

}
