/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Media Access Control
 #	author : miyako
 #	2013/02/17
 #
 # --------------------------------------------------------------------------------*/



// --- MAC
void Get_hardware_address(sLONG_PTR *pResult, PackagePtr pParams);
