/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Media Access Control
 #	author : miyako
 #	2016/10/01
 #
 # --------------------------------------------------------------------------------*/

// --- MAC
void Get_hardware_address(sLONG_PTR *pResult, PackagePtr pParams);
